"""EMTPARKING_AS_BOOL

Revision ID: 7b7afb59f9a5
Revises: 
Create Date: 2025-11-11 01:11:51.909618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b7afb59f9a5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoritos',
    sa.Column('identifier', sa.Integer(), nullable=False),
    sa.Column('family', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('streetAddress', sa.String(), nullable=False),
    sa.Column('postalCode', sa.String(), nullable=False),
    sa.Column('autonomousCommunity', sa.String(), nullable=False),
    sa.Column('wikidataAutonomousCommunity', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('categoryCode', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('wikidataCountry', sa.Text(), nullable=False),
    sa.Column('URLIcon', sa.Text(), nullable=False),
    sa.Column('long', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('openStreetMapCoordinates', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('wikidataCity', sa.Text(), nullable=False),
    sa.Column('EMTParking', sa.Boolean(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('identifier')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favoritos')
    # ### end Alembic commands ###
